### ISSUE TITLE
Invalid Unicode escape sequence 

### ISSUE THREAD

**Issue by SalilLambe** [h5p/swfobject#1]
![image](https://cloud.githubusercontent.com/assets/13847054/18672404/ae7942e6-7f65-11e6-80b5-cfb49802f6e0.png)
I get a Invalid Unicode escape sequence error at the point highlighted in the screenshot.

**Comment by icc** [comment]
Where are you using this library?

Please note that this is just an H5P wrapper for [SWFObject](https://github.com/swfobject/swfobject), and not the original project. 
It's only being used as a fallback for older browsers. 
It will be completely removed from the H5P project in a not too distant future.
